## Introduction to Numpy


**Author:** Roberto P. Muñoz<br />
**Email:** <rmunoz@uc.cl>

<a href="http://www.numpy.org">NumPy</a> is the fundamental package for scientific computing with Python.<br />
You can visit the <a href="https://github.com/numpy/numpy"> Github repository<a>

In [12]:
from __future__ import print_function 

### Review of Python data types and structures

- Numeric types
 - int
 - float 
 - long
 - complex

In [13]:
x=int(2)
print(x, type(x))

x=2
print(x, type(x))

2 <type 'int'>
2 <type 'int'>


In [14]:
x=complex(1,2)
print(x, type(x))

x=1+2*1j
print(x, type(x))

(1+2j) <type 'complex'>
(1+2j) <type 'complex'>


- Data structures
 - Tuple  // Immutable and usually heterogeous sequence of elements
 - List  // Mutable and usually homogeneous
 - Dictionary

In [25]:
# Tuple
x=(1,2,3,4)
print(x, type(x))

(1, 2, 3, 4) <type 'tuple'>


In [26]:
x[0]=100
print(x)

TypeError: 'tuple' object does not support item assignment

In [68]:
# List
x=[1,2,3,4]
print(x, type(x))

[1, 2, 3, 4] <type 'list'>


In [69]:
x[0]=100
print(x)

[100, 2, 3, 4]


In [70]:
# Add elements to the end
x.append(5)
print(x, type(x))

[100, 2, 3, 4, 5] <type 'list'>


In [71]:
# Extend
y=[6,7,8,9]
x.extend(y)
print(x, type(x))

[100, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [72]:
# Insert 200 at position 0
x.insert(0,200)
print(x, type(x))

[200, 100, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [73]:
# Inser 0 ar position 2
x.insert(2,0)
print(x, type(x))

[200, 100, 0, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [74]:
# Remove element with value of 100
x.remove(100)
print(x, type(x))

[200, 0, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [75]:
# Remove element with value of 300
x.remove(300)
print(x, type(x))

ValueError: list.remove(x): x not in list

In [76]:
# Remove element give the index
del x[0]
print(x, type(x))

[0, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [77]:
# Sort
x.sort()
print(x, type(x))

[0, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>


In [79]:
# Dictionary
population={'brazil':209.567920e6, 'mexico':128.632004e6, 'colombia':48.654392e6, 'argentina': 43.847277e6,
            'peru': 31.774225e6,  'venezuela': 31.518855e6, 'chile': 18.131850e6}
print(population, type(population))

{'brazil': 209567920.0, 'chile': 18131850.0, 'colombia': 48654392.0, 'mexico': 128632004.0, 'peru': 31774225.0, 'argentina': 43847277.0, 'venezuela': 31518855.0} <type 'dict'>


In [84]:
population.keys()

['brazil',
 'chile',
 'colombia',
 'mexico',
 'guatemala',
 'peru',
 'argentina',
 'venezuela']

In [82]:
population['chile']

18131850.0

In [83]:
population['guatemala']=16.672956e6
print(population)

{'brazil': 209567920.0, 'chile': 18131850.0, 'colombia': 48654392.0, 'mexico': 128632004.0, 'guatemala': 16672956.0, 'peru': 31774225.0, 'argentina': 43847277.0, 'venezuela': 31518855.0}


In [88]:
for key in population:
    print(key)

brazil
chile
colombia
mexico
guatemala
peru
argentina
venezuela


In [89]:
for key, value in population.iteritems():
    print(key, value)

brazil 209567920.0
chile 18131850.0
colombia 48654392.0
mexico 128632004.0
guatemala 16672956.0
peru 31774225.0
argentina 43847277.0
venezuela 31518855.0


### Numpy

Why using Numpy? Let's say you have two lists and you want to add them as vectors

In [95]:
x=[1,2,3,4]
y=[5,6,7,8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


In [96]:
import numpy as np
print(np.__version__)

1.11.1


In [128]:
# Define 1D array
x = np.array([1,2,3,4])
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[1 2 3 4]
type(x):  <type 'numpy.ndarray'>
x.dtype:  int64
x.size:  4
x.shape:  (4,)


In [100]:
# Add two arrays
y = np.array([5,6,7,8])
print(x+y)

[ 6  8 10 12]


In [109]:
# Define a 2D array
x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.size)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
<type 'numpy.ndarray'>
8
(2, 4)


In [112]:
# Initialize 1D and 2D array with zeros
x=np.zeros(10)
print(x)

x=np.zeros([2,4])
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [113]:
# Create a random array
x=np.random.random(100)
print(x)

[ 0.00184004  0.30535411  0.34197401  0.45003444  0.72501196  0.38275626
  0.71932856  0.00272694  0.26584826  0.44980935  0.1599838   0.66299047
  0.43314803  0.31037093  0.83618332  0.57333035  0.85817215  0.3158536
  0.10214068  0.18590634  0.10241169  0.6191833   0.84762627  0.85050126
  0.09407985  0.8278464   0.51392924  0.16071183  0.85529426  0.34825094
  0.21912778  0.27722969  0.52883157  0.96641633  0.77015916  0.2175592
  0.15891917  0.39770525  0.21103248  0.06852896  0.7060274   0.87799726
  0.67388995  0.51359284  0.7061061   0.91678013  0.66213885  0.94735797
  0.90625369  0.46003202  0.79346082  0.04227974  0.82531052  0.27851822
  0.64564871  0.35052117  0.29028755  0.82568035  0.59722627  0.07033725
  0.4025791   0.2121411   0.46286794  0.25025617  0.02965827  0.94575648
  0.16434211  0.9555548   0.493377    0.03162042  0.561942    0.30757976
  0.1074481   0.3628027   0.30726375  0.53983386  0.13419366  0.41803185
  0.00765926  0.10729638  0.08371646  0.67827474  0.5

In [120]:
# Array indexing
x= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

print('\nx[0,3]: ', x[0,3])

print('\nx[:,0]: ', x[:,0])
print('\nx[0,:]: ', x[0,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3]:  4

x[:,0]:  [1 5 9]

x[0,:]:  [1 2 3 4]


In [125]:
# Boolean array indexing for creating masks
mask=x>6
print(mask)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [126]:
print(x[mask])

[ 7  8  9 10 11 12]


In [105]:
# Add 2D array along axis=0
x.sum(0)

array([ 6,  8, 10, 12])

In [ ]:
# Create 